# Analysis of time series and integration

In [1]:
import copy
import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import networkx
from ItalySetup import ItalySetupProvinces, ItalySetupRegions
from covidOCP import COVIDVaccinationOCP, COVIDParametersOCP
from main import pick_scenario
import seaborn as sns
import datetime
import pickle

nx = 9
states_names = ['S', 'E', 'P', 'I', 'A', 'Q', 'H', 'R', 'V']
outdir = 'model_output/'
when = 'future'

n_int_steps = 5
nnodes = 107  # nodes
ndays = 90

setup = ItalySetupProvinces(nnodes, ndays, when)
M = setup.nnodes
N = len(setup.model_days) - 1

with open(f'italy-data/parameters_{nnodes}_{when}.pkl', 'rb') as inp:
    p = pickle.load(inp)
    
setup_reg = ItalySetupRegions(nnodes, ndays, when)

Loaded Italy Provincial Setup with 107 nodes.
Loaded Italy Provincial Setup with 107 nodes.
Loaded Italy Regionals Setup with 20 nodes.


In [19]:
setup_reg.pop_node_ag

array([[ 587188., 2736773., 1051904.],
       [  17984.,   80061.,   28157.],
       [1478770., 6423060., 2134428.],
       [ 172915.,  686320.,  208413.],
       [ 707113., 3145686., 1052238.],
       [ 158466.,  756759.,  300313.],
       [ 187966.,  945875.,  423140.],
       [ 628458., 2813272., 1010899.],
       [ 500810., 2336916.,  899242.],
       [ 119651.,  552044.,  212945.],
       [ 209991.,  964548.,  357214.],
       [ 848762., 3852231., 1195700.],
       [ 176518.,  844738.,  293940.],
       [  38060.,  199669.,   70764.],
       [ 923693., 3889834., 1013333.],
       [ 581432., 2635019.,  831791.],
       [  74135.,  371672.,  121311.],
       [ 280506., 1284008.,  392173.],
       [ 753248., 3283246.,  990495.],
       [ 202060., 1085947.,  360169.]])

In [16]:
a = np.random.randint(0,10,(2,2))
print(a)
a/np.array([.5,.25])

[[7 1]
 [6 7]]


array([[14.,  4.],
       [12., 28.]])

In [18]:
np.array([.5,.25])

array([0.5 , 0.25])

In [19]:
a/np.array([.5,.25]).T

array([[14.,  4.],
       [12., 28.]])

In [20]:
a[0,1]

1

In [13]:
np.mean((setup_reg.mobility / setup_reg.pop_node).sum(axis=1))

1.0019317690557032

In [14]:
np.mean((setup_reg.mobility / setup_reg.pop_node).sum(axis=0))

1.0019317690557035

In [15]:
np.mean((setup_reg.mobility.T / setup_reg.pop_node).T.sum(axis=0))

0.9999998891768456

In [16]:
np.mean((setup_reg.mobility.T / setup_reg.pop_node).T.sum(axis=1))

0.999999889176846

In [13]:
p.x0_ag[0][0]

array([2.72312862e+05, 1.42610081e+03, 6.08422844e+02, 2.08493880e+02,
       1.49129082e+03, 2.94434572e+02, 2.50977513e+02, 2.99022186e+04,
       0.00000000e+00])

In [16]:
p.x0_ag[0][1]

array([1.24938321e+06, 6.54301232e+03, 2.79147038e+03, 9.56578960e+02,
       6.84210694e+03, 1.35087858e+03, 1.15149571e+03, 1.37192675e+05,
       0.00000000e+00])

In [15]:
p.x0_ag[0].reshape(27)

array([2.72312862e+05, 1.42610081e+03, 6.08422844e+02, 2.08493880e+02,
       1.49129082e+03, 2.94434572e+02, 2.50977513e+02, 2.99022186e+04,
       0.00000000e+00, 1.24938321e+06, 6.54301232e+03, 2.79147038e+03,
       9.56578960e+02, 6.84210694e+03, 1.35087858e+03, 1.15149571e+03,
       1.37192675e+05, 0.00000000e+00, 4.74667823e+05, 2.48583251e+03,
       1.06054024e+03, 3.63425127e+02, 2.59946505e+03, 5.13228116e+02,
       4.37478233e+02, 5.21224775e+04, 0.00000000e+00])

In [59]:
geodata = pd.read_csv('italy-data/geodata.csv')

geodata = geodata.reset_index(drop=True)

In [69]:
geodata['population'] / agestrat.groupby(['Codice provincia', 'Provincia']).sum().reset_index()['Totale'] * 100

0       99.576047
1       99.189238
2       99.844424
3       99.752106
4       99.423765
          ...    
102     99.491703
103    100.257199
104     99.691404
105     99.689692
106     99.121047
Length: 107, dtype: float64

In [296]:
import casadi as ca
import casadi.tools as cat
import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from tqdm import tqdm
from timeit import default_timer as timer

#if "Agg" not in mpl.get_backend():
#    mpl.interactive(True)
#plt.ion()

nx = 9
states_names = ['S', 'E', 'P', 'I', 'A', 'Q', 'H', 'R', 'V']
mob_scaling = 1e7
nc = 3 # Number of age classes
M = 10
N = 10
nc = 3  # Number of age classes
ages_names = ['Y', 'M', 'O']

In [338]:
dt = (N + 1) / N / n_int_steps

states = cat.struct_symSX(states_names)
[S, E, P, I, A, Q, H, R, V] = states[...]
controls = cat.struct_symSX(['v', 'mob'])
[v, mob] = controls[...]

In [339]:
states = cat.struct_symSX([cat.entry("AG", struct=states, repeat=[nc])])

In [340]:
states = cat.struct_symSX([
    cat.entry("Y", struct=states),
    cat.entry("M", struct=states),
    cat.entry("O", struct=states)])

In [254]:
states

In [341]:
Vars = cat.struct_symMX([
            (
                cat.entry("x", struct=states, repeat=[M, N + 1]),
                cat.entry("u", struct=controls, repeat=[M, N, nc]),
            ),
        ])

In [286]:
print(Vars)

MX.sym with following structure:
Structure with total size 3570.
Structure holding 2 entries.
  Order: [('x', 'u')]
  x = repeated([10, 11]): {Y: {S: 1x1,E: 1x1,P: 1x1,I: 1x1,A: 1x1,Q: 1x1,H: 1x1,R: 1x1,V: 1x1},M: {S: 1x1,E: 1x1,P: 1x1,I: 1x1,A: 1x1,Q: 1x1,H: 1x1,R: 1x1,V: 1x1},O: {S: 1x1,E: 1x1,P: 1x1,I: 1x1,A: 1x1,Q: 1x1,H: 1x1,R: 1x1,V: 1x1}}
  u = repeated([10, 10, 3]): {v: 1x1,mob: 1x1}



In [337]:
Vars['x', 0, 0]

MX(vertsplit(V){0})

In [289]:
print(Vars['x', 0, 0, 'Y' , 'S'])

vertsplit(vertsplit(vertsplit(V){0}){0}){0}


In [290]:
a, b = [0,1], [1,0]

In [294]:
ca.veccat(*Vars['x', :, 3, 'Y', 'E'])

MX(@1=vertsplit(V), vertcat(vertsplit(vertsplit(@1{3}){0}){1}, vertsplit(vertsplit(@1{44}){0}){1}, vertsplit(vertsplit(@1{85}){0}){1}, vertsplit(vertsplit(@1{126}){0}){1}, vertsplit(vertsplit(@1{167}){0}){1}, vertsplit(vertsplit(@1{208}){0}){1}, vertsplit(vertsplit(@1{249}){0}){1}, vertsplit(vertsplit(@1{290}){0}){1}, vertsplit(vertsplit(@1{331}){0}){1}, vertsplit(vertsplit(@1{372}){0}){1}))

In [260]:
print(*Vars['x', 0, 0, 'Y'].cat)

AttributeError: 'MX' object has no attribute 'cat'

In [267]:
print(states)

symbolic SX with following structure:
Structure with total size 27.
Structure holding 3 entries.
  Order: ['Y', 'M', 'O']
  Y = {S: 1x1,E: 1x1,P: 1x1,I: 1x1,A: 1x1,Q: 1x1,H: 1x1,R: 1x1,V: 1x1}
  M = {S: 1x1,E: 1x1,P: 1x1,I: 1x1,A: 1x1,Q: 1x1,H: 1x1,R: 1x1,V: 1x1}
  O = {S: 1x1,E: 1x1,P: 1x1,I: 1x1,A: 1x1,Q: 1x1,H: 1x1,R: 1x1,V: 1x1}



SX([Y_S, Y_E, Y_P, Y_I, Y_A, Y_Q, Y_H, Y_R, Y_V, M_S, M_E, M_P, M_I, M_A, M_Q, M_H, M_R, M_V, O_S, O_E, O_P, O_I, O_A, O_Q, O_H, O_R, O_V])

In [238]:
ca.veccat(*states[...])

NotImplementedError: Wrong number or type of arguments for overloaded function '_veccat'.
  Possible C/C++ prototypes are:
    casadi::casadi_veccat(std::vector< casadi::Sparsity,std::allocator< casadi::Sparsity > > const &)
    casadi::casadi_veccat(std::vector< casadi::MX,std::allocator< casadi::MX > > const &)
    casadi::casadi_veccat(std::vector< casadi::Matrix< casadi_int >,std::allocator< casadi::Matrix< casadi_int > > > const &)
    casadi::casadi_veccat(std::vector< casadi::Matrix< double >,std::allocator< casadi::Matrix< double > > > const &)
    casadi::casadi_veccat(std::vector< casadi::Matrix< casadi::SXElem >,std::allocator< casadi::Matrix< casadi::SXElem > > > const &)


In [282]:
states['Y','S']

SX(Y_S)

In [252]:
print(states['AG'][0])

[AG_0_S, AG_0_E, AG_0_P, AG_0_I, AG_0_A, AG_0_Q, AG_0_H, AG_0_R, AG_0_V]


In [283]:
states.cat

SX([Y_S, Y_E, Y_P, Y_I, Y_A, Y_Q, Y_H, Y_R, Y_V, M_S, M_E, M_P, M_I, M_A, M_Q, M_H, M_R, M_V, O_S, O_E, O_P, O_I, O_A, O_Q, O_H, O_R, O_V])

In [298]:
k = 0
Sk, Ek, Pk, Rk, Ak, Ik, Vk = [ca.veccat(*Vars['x', :, k, ag, 'S']) for ag in ages_names], \
            [ca.veccat(*Vars['x', :, k, ag, 'E']) for ag in ages_names], \
            [ca.veccat(*Vars['x', :, k, ag, 'P']) for ag in ages_names], \
            [ca.veccat(*Vars['x', :, k, ag, 'R']) for ag in ages_names], \
            [ca.veccat(*Vars['x', :, k, ag, 'A']) for ag in ages_names], \
            [ca.veccat(*Vars['x', :, k, ag, 'I']) for ag in ages_names], \
            [ca.veccat(*Vars['x', :, k, ag, 'V']) for ag in ages_names]

In [303]:
np.sum(Sk)

MX(@1=vertsplit(V), @2=vertsplit(@1{0}), @3=vertsplit(@1{41}), @4=vertsplit(@1{82}), @5=vertsplit(@1{123}), @6=vertsplit(@1{164}), @7=vertsplit(@1{205}), @8=vertsplit(@1{246}), @9=vertsplit(@1{287}), @10=vertsplit(@1{328}), @11=vertsplit(@1{369}), ((vertcat(vertsplit(@2{0}){0}, vertsplit(@3{0}){0}, vertsplit(@4{0}){0}, vertsplit(@5{0}){0}, vertsplit(@6{0}){0}, vertsplit(@7{0}){0}, vertsplit(@8{0}){0}, vertsplit(@9{0}){0}, vertsplit(@10{0}){0}, vertsplit(@11{0}){0})+vertcat(vertsplit(@2{1}){0}, vertsplit(@3{1}){0}, vertsplit(@4{1}){0}, vertsplit(@5{1}){0}, vertsplit(@6{1}){0}, vertsplit(@7{1}){0}, vertsplit(@8{1}){0}, vertsplit(@9{1}){0}, vertsplit(@10{1}){0}, vertsplit(@11{1}){0}))+vertcat(vertsplit(@2{2}){0}, vertsplit(@3{2}){0}, vertsplit(@4{2}){0}, vertsplit(@5{2}){0}, vertsplit(@6{2}){0}, vertsplit(@7{2}){0}, vertsplit(@8{2}){0}, vertsplit(@9{2}){0}, vertsplit(@10{2}){0}, vertsplit(@11{2}){0})))

In [344]:
a = Vars['x', 0, 0]

In [357]:
S ,  E  = [], []

In [358]:
S.append(10)

In [360]:
[0, 1]+ [2,3]

[0, 1, 2, 3]